### ISSUE TITLE
Document necessary PurgeCSS configuration tweaks

### ISSUE THREAD

**Issue by adamwathan** [tailwindui/issues#1]
Tailwind UI components rely on classes that include the `.` character so we need to document the regex people need to use to account for this.

```diff
- /[\w-/:]+(?<!:)/g
+ /[\w-/.:]+(?<!:)/g
```

**Comment by adamwathan** [comment]
Added here:

https://www.notion.so/Tailwind-UI-Documentation-f9083ed0e2694690ac89253e88afb2b6#003cd0533eed41a19c4e6adbbac56ea9

**Comment by simonhamp** [comment]
I'm getting a `SyntaxError: Invalid regular expression: /[\w-/:]+(?<!:)/: Invalid group` when trying to use this (both with and without `.`)

**Comment by simonhamp** [comment]
Can confirm it was because I was running `node v8.9.4` which is 'very old'. Upgraded to `v12.16.1` and all works.

**Comment by atymic** [comment]
It seems this has been removed from the website (it's still applicable to people who configure it manually as far as i can tell?)

Nonetheless it's on archive.org:
http://web.archive.org/web/20200710095956/https://tailwindui.com/documentation
