### ISSUE TITLE
Discord invite is not valid

### ISSUE THREAD

**Issue by vvo** [tailwindui/issues#10]
(sorry to remove the template, it does not apply here)

When trying to join the discord community I get:
![image](https://user-images.githubusercontent.com/123822/75627125-da78e200-5bcd-11ea-9e01-9ba28878ad66.png)

Every time.

Thanks!

**Comment by adamwathan** [comment]
Hey sorry about this! The link is still working for me when I try on another computer so not sure what's going on here. I've DM'd you another direct invite link on Twitter to see if that helps.

**Comment by DanHarrin** [comment]
@adamwathan on Discord, go to Server Settings > Invites and you can see a list of invites, their expiry dates and number of uses.

All new invites need to be created with no expiry, no maximum number of uses and no "temporary membership" (this will kick people automatically when they disconnect from the server if they have no roles).

Hope this helps 👍

**Comment by DanHarrin** [comment]
You can also check that the invite code posted on the site is still active on that list or not.

**Comment by adamwathan** [comment]
Yeah it's listed there as still active and it works for me, so not sure what the issue might be. Hoping just temporary hiccup.

**Comment by adamwathan** [comment]
Going to close this as all signs and test show the link as being valid, so will chalk it up to some weird Discord behavior. Send us a support email if it persists (support@tailwindui.com) and I will make sure to get you invited manually 👍
