### ISSUE TITLE
Tailwind UI Component State Selector

### ISSUE THREAD

**Issue by dillingham** [tailwindui/issues#106]
Here is an idea to consider for the javascript-less component discussions

![Frame 1](https://user-images.githubusercontent.com/29180903/77196308-71440a80-6ab9-11ea-9272-084e7a3ab4c3.png)

Each state would be a separate component stored on your backend.
The output would show a diff (red = removed, green = added) from the original.
States for transitions could be documented like: Closed, Opening, Opened, Closing
The working component itself can still use Alpine for demo-ing the states.

Related: https://github.com/tailwindui/issues/issues/7

**Comment by alexbowers** [comment]
I quite like this approach to showing state rather than having any JS / Alpine intertwined.

**Comment by adamwathan** [comment]
Definitely cool approach! It would be a huge investment to build though, likely a month of effort that we couldn't spend on something else. Also trying to show transitions with this wouldn't be straightforward so still some unknowns. Transitions have a lot of states (starting enter, finished enter, starting leave, finished leave) so it would get messy.

It also means you can't really just copy and paste the code anymore, you'd have to copy all the states separately or use the mouse to select just the green additions when building each state.

My fear is that even if we did invest a month into building this, once you could actually try it and interact with it it could still feel slow or inconvenient to use, so it's a high risk thing to focus on right now :/

Appreciate the suggestion though and definitely a solution I will keep in mind.

**Comment by dillingham** [comment]
@adamwathan makes sense, thanks for the reply and consideration.
