### ISSUE TITLE
Disabled button states

### ISSUE THREAD

**Issue by dmfj** [tailwindui/issues#109]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/buttons

**Describe the bug**
It would be nice to have an example for a disabled state of each of the button components.

**Comment by DashBolt** [comment]
it does'nt like that buddy

**Comment by jasonlbeggs** [comment]
I'm going to close this issue for now since it's not really a bug, but I'll leave #171 open as a reminder to revisit this improvement in the future. Thanks!

**Comment by fvilers** [comment]
@sohara It seems that it doesn't have this state anymore.

**Comment by MPJHorner** [comment]
Yep missing, bummer.

**Comment by stassinari** [comment]
This absence is pretty annoying, as `disabled` buttons are very common.

After scouring through literally _every_ page, I found there is an example of a `disabled` button in ["Checkout Forms > Multi-step" section](https://tailwindui.com/components/ecommerce/components/checkout-forms#component-b499102417cdeb5454814b13a7828673)

**Comment by kevinbailey25** [comment]
Searched around thinking "there's no way there's no disabled buttons..." glad I wasn't the only one finding out they weren't here. haha hope they get added. Pretty common thing imo. But made my own for now.
