### ISSUE TITLE
Wide Lists: non-existent mr-1.5 used, no margin rendered

### ISSUE THREAD

**Issue by ahtik** [tailwindui/issues#110]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/wide
- Component name: all

**Describe the bug**
Code is using `mr-1.5` that [does not exist in the latest tailwindcss](https://tailwindcss.com/docs/margin/#app).

This is causing the copy-paste render without the right margin.

**Comment by RobinMalfait** [comment]
They are available via the `tailwind/ui` plugin. But you have to watch out if you have a `tailwind.config.js` file where you define all the things. If you used `extend` you should not see a problem.

**Comment by adamwathan** [comment]
Yep @RobinMalfait is correct, you need to install the `@tailwindcss/ui` plugin.

See the documentation here: https://tailwindui.com/documentation

I've tried to make this as obvious as possible with the banner we include on every single page but you're not the first one to miss it, so there's probably something better we can do here.

![image](https://user-images.githubusercontent.com/4323180/77360081-19104100-6d23-11ea-9b86-e8d0418288d4.png)

**Comment by ahtik** [comment]
I do have the latest `tailwind/ui` included. But I think the problem is that I'm using the generated `tailwind.config.js` and not sure how to use the above-recommended `extend`.

I also do not have `gray-50` generated, I guess that's also part of the tailwindcss/ui and I should somehow extend my color palette, not override it?

**Comment by ahtik** [comment]
I noticed the relevant bit now from the docs, appologies! I thought I had it all read through carefully, but still missed this part:
```
Make sure you don't generate your Tailwind config using the `--full` flag or the extensions added by the plugin will be superseded by the values in your config. Keep any of your own modifications under `theme.extend` to ensure everything works as expected.
```

**Comment by adamwathan** [comment]
Ah yeah that makes sense, sorry for the confusion there! Let me know if you run into any issues trying to migrate your configuration over.

You can also see the source for the extensions added by the plugin here in case it's useful:

https://unpkg.com/browse/@tailwindcss/ui@0.1.3/index.js

**Comment by ahtik** [comment]
No issues with the migration, done now and everything works as it should. Thanks.

**Comment by andrewwiik** [comment]
I still can't get the above class to generate and I am not extending or overriding anything, here is my config file: 

```
module.exports = {
  theme: {},
  variants: {},
  plugins: [
    require('@tailwindcss/ui'),
  ],
}
```
