### ISSUE TITLE
User image larger than nav div

### ISSUE THREAD

**Issue by jfreeze** [tailwindui/issues#114]
**What component (if applicable)**
Application UI > Application Shells > Sidebar Layouts
- URL for category: 
https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: 
All Sidebars with Tom Cook image

**Describe the bug**
On the desktop view, the image is not constrained to the nav div.

**To Reproduce**

**Expected behavior**
The expected view is what is seen on mobile. The mobile version is correct.
![Screen Shot 2020-03-24 at 4 06 54 PM](https://user-images.githubusercontent.com/766/77476913-85ee0e80-6de9-11ea-840d-0c12f0d8cc4a.png)
![Screen Shot 2020-03-24 at 4 06 42 PM](https://user-images.githubusercontent.com/766/77476923-8b4b5900-6de9-11ea-8797-463adb1bd0e2.png)

**Screenshots**

**Browser/Device (if applicable)**
iOS
Chrome and Safari

**Additional context**

**Comment by jfreeze** [comment]
The reason this is happening is the image has

`<img class="inline-block h-9 w-9 rounded-full"`

Is this intended?

**Comment by jasonlbeggs** [comment]
I think you need to install the `@tailwindcss/ui` plugin as [stated in the docs](https://tailwindui.com/documentation). `w-9` and `h-9` will probably be added to the default Tailwind configuration in the future, but for now adding the plugin should work. Thanks!
