### ISSUE TITLE
Add a visual indeterminate state on a checkbox

### ISSUE THREAD

**Issue by corstian** [tailwindui/issues#125]
Although the indeterminate state cannot be set directly on a checkbox, it can be set from javascript code, and provides valuable feedback to the user.

My request is to add a visual feedback to the `indeterminate` state on the checkbox.

Prior art can be found [here](https://css-tricks.com/almanac/selectors/i/indeterminate/).

Even though this issue is slightly related to https://github.com/tailwindui/issues/issues/115, this issue only focuses on the behavior of the checkbox, which might be relevant in nested checkbox lists.

**Comment by swanson** [comment]
@corstian In case you haven't seen this: https://github.com/tailwindcss/custom-forms/issues/27 I've been using that customization for indeterminate state in my project. Works okay in a pinch!

![image](https://user-images.githubusercontent.com/56947/78606276-091c5500-782b-11ea-8af3-66294b2a8fc9.png)

**Comment by corstian** [comment]
Hadn't seen it yet. Thanks!
