### ISSUE TITLE
Duplicate attribute in Branded nav with compact white page header

### ISSUE THREAD

**Issue by Olindn** [tailwindui/issues#127]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/stacked#component-e1d4a342c5903e8ade21c57c20448d69
- Component name: Branded nav with compact white page header

**Describe the bug**
Duplicate role attribute on line 72
`<div class="mt-3 px-2" role="menu" aria-orientation="vertical" aria-labelledby="user-menu" role="menuitem">`

**Expected behavior**
Remove the duplicate role.

**Comment by jasonlbeggs** [comment]
Thanks for submitting this issue! It's been fixed now.
