### ISSUE TITLE
Sidebar does not close on small screen

### ISSUE THREAD

**Issue by tiagomatosweb** [tailwindui/issues#128]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: Brand sidebar with light header

**Describe the bug**
On small screen, clicking outside of the sidebar does not close the sidebar.

**To Reproduce**
1. Shrink the screen until the desktop sidebar is gone
2. Click on the top left bitten hamburger to open the sidebar
3. Click outside of the actual sidebar.
4. It should be closed, but it does not.

**Expected behavior**
The sidebar should close when clicking outside

**Comment by narwy** [comment]
This will need to be handled from your javascript framework, you will need to create a function that when you don't click the side bar element, it will close it. It could be added to the example.

A good guide on how this is handled is here (Vue.js): https://tailwindcss.com/course/adapting-the-dropdown-for-mobile/#app

**Comment by tiagomatosweb** [comment]
I know that for sure. I'm just mention this to fix the example.

**Comment by jasonlbeggs** [comment]
I'm closing this issue for now since no Alpine code is included in the code snippets anymore. Thanks for submitting!
