### ISSUE TITLE
Hero components nav not easily re-usable in Blade layout

### ISSUE THREAD

**Issue by dakira** [tailwindui/issues#130]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes#component-b9bcab4538776a17fff93d18f82a8272
- Component name: Simple centered

**Describe the bug**
Using the regular Laravel Blade flow of `@extend('layouts.app')` I haven't found a way to use the navigation from the component on other pages without breaking it.

As the navigation is embedded inside the hero section it cannot be easily split from it to be used on other pages of the site.

If one just duplicates the whole structure and includes only the navigation (leaving out the hero), the component is not high enough to display the nav in mobile mode (it gets cut off). So the nav alone without the hero doesn't work.

**Screenshots**
![screencast](https://user-images.githubusercontent.com/576555/78192830-4377a200-7479-11ea-93c7-87ebb7653eaf.gif)

**Comment by dakira** [comment]
So the problem with the nav not showing when the hero is unused comes from the `overflow-hidden` on the parent element. When removing that, the dotted pattern bleeds to the right, so I removed that pattern, too and now I can use the nav on other pages.

I still think it should be easier to use this in layouts, so I'll leave this open, close if you like. @adamwathan :)

**Comment by ademers** [comment]
Component request #129 could be a solution.

**Comment by narwy** [comment]
This is because you're using the Hero component which has the navigation bar built into it. If you want a reusable nav bar you could copy that and create a component. If you want a reusable navbar, these are your best bet: https://tailwindui.com/components/application-ui/navigation/navbars

**Comment by dakira** [comment]
@narwy The Hero component having a nav implies that that are other pages (unless this is only intended for one-pagers), so it would make sense to use that nav on other pages.

This issue just states, that the structure of the component prevents the nav from being easily reusable, that's all.

**Comment by narwy** [comment]
@dakira This is because it's apart of the marketing ui kit, it's designed to be a marketing page. You're after something to be re-usable I would suggest using the navigation bars from the application ui kit.

**Comment by JonasEriksson** [comment]
tagging along here, I would appreciate a copy copy version of the hero sections without the navbar. To me this breaks the concept of individual copy & paste modules somewhat, as the hero sections could be useful elsewhere on a site, but require striupping out the navbar elements then.

**Comment by jasonlbeggs** [comment]
I'm going to close this issue for now as it's not really a bug, but I definitely see how it could be difficult to work with. I'll leave #129 open in case @adamwathan wants to provide an easier way to copy marketing navs in the future. Thanks!
