### ISSUE TITLE
Typo - Modals

### ISSUE THREAD

**Issue by LewisLarsen** [tailwindui/issues#135]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name:  Any modals with the deactivate account example

**Describe the bug**
permanantly should be permanently. 

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/overlays/modals
2. Look at first modal
3. Scroll down to other deactivate account examples
4. See typo 

**Expected behavior**
n/a

**Screenshots**
![alt text](https://i.imgur.com/6MkNpWU.png)

**Browser/Device (if applicable)**
 - OS: Windows 10 Pro
 - Browser: Brave
 - Version: 1.5.115

**Comment by LewisLarsen** [comment]
Looks to be fixed on the first example upon entering the page, however it should be noted that the screenshots still present the typo.

**Comment by jasonlbeggs** [comment]
I'm closing this since it's been fixed in the example. Thanks!
