### ISSUE TITLE
Mega Menu with Submenus - Navigation Hierarchies

### ISSUE THREAD

**Issue by mjatharvest** [tailwindui/issues#139]
If this isn't addressed in headers, a navigation with 2 or 3 levels, and images mixed in.

a mega menu if you will

**Screenshots**
![Screen Shot 2020-04-09 at 1 33 58 PM](https://user-images.githubusercontent.com/285877/78928941-23db0d80-7a67-11ea-871c-97cedc7e7215.png)

**Additional context**
For complex navigation on marketing sites

**Comment by JonasEriksson** [comment]
Second that! Perhaps also simply 2-3 columns in the drop down (also a style of mega-menu I suppose).

Best regards / Med vänliga hälsningar
Jonas Eriksson
INNOMEGA AB
________________________________

**Comment by loilo** [comment]
Agreed. Wanted to suggest various flavors of submenus, as I observe them to be relatively hard to get just right — but I think this is included in this issue. Maybe it should be renamed to "Navigation hierarchies" or the like. 🙂

**Comment by loilo** [comment]
Just saw [this tweet](https://twitter.com/steveschoger/status/1250127231139172361) — they seem to be on something like this. 👌

**Comment by connecteev** [comment]
Would be cool if it worked like the megamenu on https://stripe.com/

**Comment by loilo** [comment]
@connecteev It would indeed, but I think the amount of fancy JS needed for that would exceed what Tailwind UI is trying to provide by a long shot. 😁

**Comment by loilo** [comment]
This issue may be solved through the new [Headers](https://tailwindui.com/components/marketing/elements/headers) category. 👌

**Comment by mjatharvest** [comment]
Indeed! Thanks.
