### ISSUE TITLE
a dropdown notifications component with example notifications

### ISSUE THREAD

**Issue by vesper8** [tailwindui/issues#14]
**Screenshots**
<img width="460" alt="Screen Shot 2020-03-01 at 8 55 32 PM" src="https://user-images.githubusercontent.com/816028/75631864-3c057480-5bff-11ea-9406-2a43dfceba19.png">
<img width="480" alt="Screen Shot 2020-03-01 at 8 54 55 PM" src="https://user-images.githubusercontent.com/816028/75631883-50497180-5bff-11ea-8e2f-8f4ac6ef2e5e.png">

**Additional context**
It would be lovely if you included a functional notifications dropdown so when you click on the bell icon it displays notifications with perhaps a 'clear all' button. It would be nice to have a few notifications components.. some very simple with text and maybe an avatar and others more complex with a larger image and buttons

**Comment by vesper8** [comment]
@adamwathan Hi adam, I just wanted to bring attention to this request again after you've recently pushed a few notifications examples to Tailwind UI. As you can see from the thumbs up above, this is something many of us would like.

The few notifications examples you recently pushed look nice, however they are difficult to use. I am currently trying to implement one of them and running into a lot of pain. The problem is that you made the notifications with a fixed position, so they only work if you only have a single notification, in order to stack them you have to remove the fixed attribute and doing that messes up the layout a lot, it may be simple for you to remedy because you're familiar with the project, but I am really struggling to take any of your single notifications and nicely make them stack one under another

**Comment by adamwathan** [comment]
Will definitely add some examples of this in a future update 👍 Unfortunately can only do one thing at a time but it's on the list for sure.

I've added it to our Trello roadmap so folks can vote and help us prioritize:

https://trello.com/c/9n4O0J8b/37-application-ui-dropdowns-with-list-items

Closing here since it's officially in the backlog now!
