### ISSUE TITLE
Quote svg is overlapping quote text

### ISSUE THREAD

**Issue by JeanPaulvB** [tailwindui/issues#144]
**What component**
https://tailwindui.com/components/marketing/sections/testimonials#component-54ee9cbce13afa3082f12b00ff1c00a6

**Describe the bug**
The large quote svg is overlapping the text in the quote, this shouldn't be the case (text should have higher z-index than the background svg)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/12576212/79020344-e36bb480-7b78-11ea-8424-6e7fd9bc8cd4.PNG)

**Comment by jasonlbeggs** [comment]
This has been fixed now! Thanks for the suggestion.
