### ISSUE TITLE
JavaScript library

### ISSUE THREAD

**Issue by schristm** [tailwindui/issues#15]
I love the idea of Tailwind UI. The components are beautiful, and thoughtfully designed. I think I had a couple of preconceptions about what Tailwind UI would be that I'd like to get clarification on whether it's part of the roadmap or not.

1) While being able to copy and paste the html from the component browser is an easy and straightforward process, I was assuming we'd ultimately have a drop in stylesheet that would include these reusable components. I guess I was thinking of something like this: https://github.com/andreaseriksson/bootstrap-tailwind-components

2) The one thing I have always felt hindered by Tailwind when compared to frameworks like Bootstrap is the lack of JavaScript utilities for common things like modals, tabs, tooltips, and so on. I was really hoping we'd get something like that with Tailwind UI. If that's not in the plan, I'm thinking about utilizing something like Bootstrap Native (https://github.com/thednp/bootstrap.native) since it's decoupled from Bootstrap for the most part and just relies on certain naming conventions, which I think are reasonable. Ultimately, this still feels a bit "hackish" but so does constantly reinventing the wheel for each project. I'm just curious if there are plans for tackling this anytime or if anyone would be interested in an open source project to port Bootstrap Native over to Tailwind. I'd be willing to help sponsor that.

Anyhow, looking great guys, and I can't wait to see how this product continues to develop over the coming months!

**Comment by adamwathan** [comment]
Hey @schristm! Just a heads up this question is probably better as a support email, but answers for you below anyways 👍 

1. The components rely only on Tailwind CSS v1.2 and (for now at least) the `@tailwindcss/ui` Tailwind plugin. We do provide a pre-built stylesheet that includes the plugin too though. More [in the documentation](https://www.notion.so/Tailwind-UI-Documentation-f9083ed0e2694690ac89253e88afb2b6#c5a80bfe3a30407286c32a6634925019).

2. We cover this on [the FAQ on our pricing page](https://tailwindui.com/pricing) so just pasting that here for you 👍 

> **What JS framework does Tailwind UI use?**
>
> In order to be as universal as possible, Tailwind UI is an HTML-only component library and **does not include any JavaScript.**
> 
> Most of the components do not rely on JS at all, but for the ones that do (dropdowns, modals, etc.) we provide a very basic example using Alpine.js just to show you what utility classes you need to toggle in a component's various states.
> 
> To get a better idea of how this looks in practice, [check out our documentation](https://tailwindui.com/documentation).

If this isn't inline with your expectations totally shoot us a support email at support@tailwindui.com and we will refund you. Thanks man!

**Comment by DanHarrin** [comment]
Please join the discussion on #7.

I doubt that developing a whole JS library for Tailwind UI would be the best approach for people who are already using a framework like Alpine / Vue / React. The approach the product has taken to developing its components without any real framework-tie-in allows for maximum flexibility. I don't see the Alpine examples as "reinventing the wheel" - Alpine is lightweight and has a naturally minimal syntax that is perfect for small interactivity features that shouldn't require too much JavaScript - menu toggles and the like.

**Comment by DanHarrin** [comment]
Ah, looks like Adam beat me to it! 😆
