### ISSUE TITLE
Multiple notifications results in horizontal display

### ISSUE THREAD

**Issue by vvo** [tailwindui/issues#155]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/notifications
- Component name: Simple

**Describe the bug**
When you try to display multiple notifications, they line up horizontally while I guess vertically would make more sense.

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/overlays/notifications
2. Update dom to copy notification
3. Notifications are side by side

**Expected behavior**
Notifications should be displayed vertically

**Screenshots**
![image](https://user-images.githubusercontent.com/123822/79441565-b2a3d900-7fd7-11ea-893e-65966cb8c2e1.png)

**Comment by guillaumebriday** [comment]
Yep, that's annoying :)

I wish the result could be something like this: https://getbootstrap.com/docs/4.4/components/toasts/#stacking

**Comment by vvo** [comment]
@guillaumebriday one possible "fix" is to change the top div to:

```html
<div className="absolute inset-0 flex flex-col items-end px-4 py-6 sm:p-6">
```

that's it

**Comment by vvo** [comment]
Result:
![image](https://user-images.githubusercontent.com/123822/79465574-ce20db00-7ffb-11ea-90eb-9c765745b307.png)

(Careful: I removed the mobile classes and pointer events, no idea why there's pointer events disabling here)

**Comment by vvo** [comment]
Update: I am not skilled enough to solve this properly so I reverted to the original css, let's wait for a reply from authors :)

**Comment by alecho** [comment]
I added a `div.max-w-sm.w-full.grid.grid-cols-1.gap-4` as a child of the `div.fixed.inset-0.flex...` wrapping everything else. Seems to work well.

**Comment by vvo** [comment]
@alecho, confirming, it works well, thanks!
