### ISSUE TITLE
Add component's title on Tailwind UI website in tabs.

### ISSUE THREAD

**Issue by guillaumebriday** [tailwindui/issues#156]
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**
Add component's title on Tailwind UI website in tabs.

**To Reproduce**
1. Go to https://tailwindui.com/components
2. Click on a component section

**Expected behavior**
Having title to distinct multiple components in tabs

**Screenshots**
![Screenshot 2020-04-16 at 15 01 34](https://user-images.githubusercontent.com/8252238/79459476-a0d02f00-7ff3-11ea-92e3-110eff3e4ba1.png)

**Comment by jasonlbeggs** [comment]
This has been updated. Thanks!

**Comment by guillaumebriday** [comment]
Great! 🙏
