### ISSUE TITLE
Please consider stricter Alpine js

### ISSUE THREAD

**Issue by tanthammar** [tailwindui/issues#159]
I know you announced switching to html markup instead of Alpinejs. But for us that uses Alpine, please consider changing to a stricter code syntax. 

Like x-on:click instead of @click. 

The @prefix conflicts with other code languages. Like in Laravel Livewire.
When I copy the code I always have to do a find/replace. 

Yes it is not a big issue but when you’re already so close to a copy/paste ready solution it would be nice if it worked all the way.

Also please add .stop to all components that can be expected to cover other page elements, like modals, notifications.

**Comment by jasonlbeggs** [comment]
I'm closing this issue for now since Tailwind UI no longer includes any Alpine in the code snippets. Thanks for the suggestion though!
