### ISSUE TITLE
Wrong id-value for username-field

### ISSUE THREAD

**Issue by SahinU88** [tailwindui/issues#162]
**What component (if applicable)**
- https://tailwindui.com/components/application-ui/forms/form-layouts#component-db11f83176d113e39bf2559da9344b1c
- Component name: Two-column cards with separate submit actions

**Describe the bug**
Just noticed that the`username` input field has a wrong value for the id which causes that the focus won't work if you click on the label. At the moment the label has ´username´ as the for-value and the input-field has `company_website`.

Screenshots
![image](https://user-images.githubusercontent.com/5758310/79695149-607fe380-8275-11ea-9733-8790c4f64b41.png)

Really not a biggie, but I guess it helps when the documentation and samples are as much as error-free :)

**Comment by bradlc** [comment]
Thanks! This has been amended 👍
