### ISSUE TITLE
Nav user drop down not "nice"...

### ISSUE THREAD

**Issue by telkins** [tailwindui/issues#169]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/navbars
- Component name: all of them, I suspect

**Describe the bug**
The hover color change for the drop-down user items are rectangular and the top item, when hovering, has its top two corners pushing up past the drop-down's rounded corners.  Please see screenshot.

**To Reproduce**
1. Go to navbar components
2. Click on user avatar to show drop-down
3. Hover over top drop-down item

**Expected behavior**
The top of the hover "behavior" will not push up past the rounded corners of the drop-down.  (Sorry, not a front-ender, so I don't know the right terminology.)

**Screenshots**
![image](https://user-images.githubusercontent.com/53731/79971272-61db2700-8494-11ea-96aa-5798641303be.png)

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser Chrome
 - Version 80

**Additional context**
n/a

**Comment by adamwathan** [comment]
Wow amazing eye! 😅  Just fixed this internally so it'll be in the next update. Trick is just adding `overflow-hidden` to the container holding the links:

```diff
- <div class="py-1 rounded-md bg-white shadow-xs">
+ <div class="py-1 rounded-md bg-white shadow-xs overflow-hidden">
```
