### ISSUE TITLE
search function (cmd-k) returns a lot of wrong results

### ISSUE THREAD

**Issue by vesper8** [tailwindui/issues#170]
I really like the new site-wide search (cmd-k) but I have two gripes with it. First, it seems to be way too fuzzy and returns a lot of wrong results. For example, searching for `content` will display 3 search results, the last 2 of which are actually `Contact` pages

My bigger gripe is that 80% of what it shows is "coming soon". These "coming soon" sections should either not be included in the search, or should be labeled accordingly in the search results, imho

**Comment by jasonlbeggs** [comment]
It looks like categories without published components are no longer included in search results. Thanks for the suggestion!
