### ISSUE TITLE
Checkbox + Label suggestion / Tweak

### ISSUE THREAD

**Issue by ciamarro** [tailwindui/issues#174]
**What component (if applicable)**
- https://tailwindui.com/components/application-ui/forms/form-layouts
- Checkbox + Label

**Describe the bug**
Not a bug, just a suggestion / tweak
There's a small 'deadzone' between the checkbox and the label

**To Reproduce**
Click in between the checkbox and label

**Expected behavior**
Clicking anywhere in the 'group' would change the state of the checkbox

**Additional context**
Current markup:
```html
<div class="relative flex items-start">
    <div class="absolute flex items-center h-5">
        <input id="comments" type="checkbox" class="form-checkbox h-4 w-4 text-indigo-600 transition duration-150 ease-in-out" />
    </div>
    <div class="pl-7 text-sm leading-5">
        <label for="comments" class="font-medium text-gray-700">Comments</label>
        <p class="text-gray-500">Get notified when someones posts a comment on a posting.</p>
    </div>
</div>
```

**Suggestion**
```html
<label for="offers" class="relative flex items-start">
    <span class="absolute flex items-center h-5">
        <input id="offers" type="checkbox" class="form-checkbox h-4 w-4 text-indigo-600 transition duration-150 ease-in-out">
    </span>
    <span class="pl-7 text-sm leading-5">
        <span class="block font-medium text-gray-700">Offers</span>
        <span class="text-gray-500">Get notified when a candidate accepts or rejects an offer.</span>
    </span>
</label>
```

**Comment by adamwathan** [comment]
Hey @ciamarro! I think this is a cool suggestion but I think both approaches are reasonable so not going to change it unnecessarily. You can definitely make this tweak in your own projects of course though after pulling in our markup as a starting point 👍
