### ISSUE TITLE
Testimonial with large avatar - text under svg

### ISSUE THREAD

**Issue by sebastian** [tailwindui/issues#177]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/testimonials#component-54ee9cbce13afa3082f12b00ff1c00a6
- Component name: With large avatar

**Describe the bug**
The large graphic quotation mark are on top of the text.
It seems they should be a background element.

**Expected behavior**
I would expect the graphic element to be behind the text, like is the case with the "Side-by-side on brand" variant.

**Screenshots**
<img width="417" alt="Screen Shot 2020-04-26 at 22 16 52" src="https://user-images.githubusercontent.com/1089/80318636-c9ce9c00-880b-11ea-87ba-a386614d7787.png">

**Browser/Device (if applicable)**
 - OS: macOS
 - Browser: Firefox (v75), Safari (macOS catalina)

**Comment by jasonlbeggs** [comment]
This has been fixed now! Thanks.
