### ISSUE TITLE
Stats -> With Brand Icon mobile view

### ISSUE THREAD

**Issue by shaharmor** [tailwindui/issues#178]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/data-display/stats#component-0d73a2494863902616f059ddcb5da2d5
- Component name: Stats With Brand Icon

**Describe the bug**
The 3 stats cards should be in one of two states:
1. 3 horizontal boxes
1. 3 vertical boxes

When reducing the width of the container, there is a specific width where the view is 2 horizontal boxes and 1 vertical box:

<img width="1399" alt="Screen Shot 2020-04-27 at 12 29 46" src="https://user-images.githubusercontent.com/10861920/80356896-cf1afd80-8882-11ea-886e-0f4e71595850.png">

This doesn't happen with the other Stats components

**To Reproduce**
1. Go to https://tailwindui.com/components/application-ui/data-display/stats#component-0d73a2494863902616f059ddcb5da2d5
2. Reduce the width of the *With Brand Icon* container
3. See error

**Expected behavior**
The boxes should be either horizontal, or vertical. Not both.

**Screenshots**
Attached above

**Browser/Device (if applicable)**
 - OS: OSX
 - Browser: Chrome
 - Version: 84

**Comment by jasonlbeggs** [comment]
That was a design choice to not cram the contents or have way too much whitespace at that breakpoint. If you'd like to make them stack vertically at that breakpoint, feel free to make that change in your application. Thanks for the suggestion!

**Comment by shaharmor** [comment]
@jasonlbeggs it was a design choice specifically for the theme with the Brand Icon? Because it doesn’t happen for the other ones

**Comment by jasonlbeggs** [comment]
Yes I think so because of the amount of content inside each card. If you want to change the content layout similar to the "With shared borders" component, that'd be another option. I don't think it's necessary for them all to wrap exactly the same though. Thanks for the suggestion!
