### ISSUE TITLE
Add Alpine.js integration back (solved)

### ISSUE THREAD

**Issue by KevinBatdorf** [tailwindui/issues#183]
If you want to have the Alpine.js code added back to your clipboard you can add this script to your browser to have it auto populated.

https://gist.github.com/KevinBatdorf/8bd5f808fff6a59e100dfa08a7431822

Demo: https://youtu.be/0W01uFLbSdA

**Comment by prenaux** [comment]
Please make this a button in the standard version.

**Comment by JeanPaulvB** [comment]
I miss Alpine.js in the "code" section of the components, why not leave it there for those that _do_ want to use Alpine.js? A lot of examples are not [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) anymore...

**Comment by jasonlbeggs** [comment]
Adam has been talking about bringing back Alpine (even better than before). I'm closing this issue for now. Thanks for the suggestions!

**Comment by KevinBatdorf** [comment]
Just want to point out @jasonlbeggs that this wasn't a suggestion but a working, temporary solution to those who wanted to utilize Alpine now while the new system is being built.
