### ISSUE TITLE
Can not access the Tailwind UI color palette when excluding other colors.

### ISSUE THREAD

**Issue by RalphMRivera** [tailwindui/issues#186]
**What component (if applicable)**
- URL for category: https://tailwindcss.com/docs/customizing-colors
- Component name: Customizing Colors

**Describe the bug**
When I exclude colors in the Tailwind config, I only get the Tailwind color palette and not the Tailwind UI colors. This includes the "-50" colors.

**To Reproduce**
Use this config:

```
const {colors} = require('tailwindcss/defaultTheme')

module.exports = {
    theme: {
        colors: {
            black: colors.black,
            white: colors.white,
            red: colors.red,
            gray: colors.gray,
        },
    },
    plugins: [
        require('@tailwindcss/ui'),
    ]
}
```

**Expected behavior**
I expect to be able to use `bg-gray-50` as well as the gray palette of Tailwind UI. But `bg-gray-50` has no effect. I also only get the Tailwind default colors instead of the Tailwind UI colors.

**Screenshots**
//

**Browser/Device (if applicable)**
//

**Additional context**
//

**Comment by mioduszewski** [comment]
Are you aware, that you can use the `extend` functionality if you just want to extend some colors? If you want to get rid of all the colors presented by tailwind, you have to so something like this:

``` 
const { colors } = require('tailwindcss/defaultTheme')
const { uicolors } = require('@tailwindcss/ui/colors');

module.exports = {
    important: true,
    theme: {
        colors: {
                ...uicolors, ...{
                black: colors.black,
                white: colors.white,
                red: colors.red,
                gray: colors.gray,
            }
        }
    },
    plugins: [
        require('@tailwindcss/ui'),
    ],
}```

**Comment by RalphMRivera** [comment]
Can you clarify? I tried a few things based on your recommendation, but none worked. My goal is to exclude all colors except the white black, red, and gray or Tailwind UI.

My goal is to be able to use `bg-gray-50`, but other colors like `bg-indigo-50` would not be available.

I tried this without success.:

```
const {colors} = require('tailwindcss/defaultTheme')
const { uicolors } = require('@tailwindcss/ui/colors');

module.exports = {
    theme: {
        colors: {
                black: uicolors.black,
                white: uicolors.white,
                red: uicolors.red,
                gray: uicolors.gray,
        },
    },
    plugins: [
        require('@tailwindcss/ui'),
    ]
}
```

**Comment by RalphMRivera** [comment]
I also tried excluding everything and extending the colors I want, but that didn't work either.

```
const {colors} = require('tailwindcss/defaultTheme')
const { uicolors } = require('@tailwindcss/ui/colors');

module.exports = {
    theme: {
        colors: {
        },
        extend: {
            colors: {
                white: uicolors.white,
                black: uicolors.black,
                gray: uicolors.gray,
                red: uicolors.red,
            }
    },
    plugins: [
        require('@tailwindcss/ui'),
    ]
}
```

**Comment by adamwathan** [comment]
Hey @RalphMRivera you almost have it, just need to remove the curly braces around `{ uicolors }`:

```js
const uicolors = require('@tailwindcss/ui/colors');

module.exports = {
    theme: {
        colors: {
                black: uicolors.black,
                white: uicolors.white,
                red: uicolors.red,
                gray: uicolors.gray,
        },
    },
    plugins: [
        require('@tailwindcss/ui'),
    ]
}
```

**Comment by RalphMRivera** [comment]
That works perfectly, Thanks @adamwathan and @mioduszewski .
