### ISSUE TITLE
Reflexions about accessibility on radios / checkboxes

### ISSUE THREAD

**Issue by LouisCuvelier** [tailwindui/issues#189]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: All radios and checkboxes

**Expected behavior**
I've read that you have now an accessibility consultant by your side. So, here's some reflexions :

1. In my opinion, the gap between radio/checkbox and its label (see screenshot below) should be clickable. Adding a padding to fill this gap seems to be a more accessible solution.
2. By default, when we hover a radio or checkbox, the cursor doesn't change. I tend to think that add a `cursor: pointer;` make it more obvious and more accessible.

What do you think ?

**Screenshots**
(Red = space un-clickable)
![image](https://user-images.githubusercontent.com/34551650/81120811-b15a3200-8f2d-11ea-94cc-fb4bf8887dfd.png)

**Comment by jasonlbeggs** [comment]
Thanks for the suggestion, but it's a similar issue to #174, so I'm going to close it for now. Feel free to make those changes in your own apps!
