### ISSUE TITLE
Stop popup show on pageload

### ISSUE THREAD

**Issue by schmeits** [tailwindui/issues#19]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/stacked
- Component name: Dark nav with overlap (currently using this one... think the problem exists with all the Stacked Layouts)

**Describe the bug**
If I place the code in a new project and I refresh the page I see the profile dropdown showing briefly.

**To Reproduce**
1. place code in project and refresh the browser to see the popup appear for a few milliseconds

**Expected behavior**
I hoped the popup would only show if the (profile)button was clicked :)

**Browser/Device (if applicable)**
 - OS: windows
 - Browser: Chrome
 - Version: 80.0.3987.122 (Officiële build) (64-bits)

I can't reproduce on Firefox

**Additional context**
I fixed it by putting the hidden class on the popup and adding the :class alpine to remove the class if opened.

Original:
`<div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg"  >`

Fix:
` <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg"  :class="{ 'hidden': !open}" >`

**Comment by jasonlbeggs** [comment]
Thanks for the report! I'm closing this issue now since Tailwind UI no longer includes Alpine code in the code snippets anymore.
