### ISSUE TITLE
Ability to customize form inputs

### ISSUE THREAD

**Issue by g7s** [tailwindui/issues#190]
AFAIK there is currently no way to customize form inputs. For example there is no way I can change the border radius on the form elements from the tailwind config.

**Comment by jasonlbeggs** [comment]
Tailwind UI uses the [Tailwind Custom Forms Plugin](https://github.com/tailwindcss/custom-forms) under the hood. Checkout the documentation for the plugin to see how it can be customized. Thanks!

**Comment by g7s** [comment]
The only way to customize anything on the custom forms plugin (assuming you use Tailwind UI) is to copy paste the whole thing from the Tailwind UI library into your own config and tweak it there. If a later version of Tailwind UI changes anything on the plugin config you have to do it all over again which sucks.

If there is another way please share. For example how would you go about changing the border radius on form elements?

**Comment by Gustorn** [comment]
@g7s I just had a use-case about customizing form inputs and here's how I ended up solving it. This is specifically about setting different border radiuses but in a way where we defined a new border radius for each of the original variants (none, sm, default, md, lg, full):

```js
// tailwind.config.js
const tailwindUiPlugin = require("@tailwindcss/ui")({ layout: "sidebar" });
const { borderRadius: defaultBorderRadius } = require("tailwindcss/defaultTheme");

const borderRadius = { /* none, sm, default, md, lg, full */ };
module.exports = {
  theme: {
    borderRadius,
    customForms: theme => {
      const uiConfig = Object.entries(tailwindUiPlugin.config.theme.customForms(theme).default);
      const customConfig = Object.fromEntries(
        uiConfig.map(([key, element]) => {
          for (const [variant, radius] of Object.entries(defaultBorderRadius)) {
            if (radius === element.borderRadius) {
              return [key, { ...element, borderRadius: borderRadius[variant] }];
            }
          }

          return [key, element];
        }),
      );
      return {
        ...uiConfig,
        default: customConfig,
      };
    },
  }
};
```

This way you can change only the properties you need and you'll get all the upstream changes automatically. It gets a little uglier if you need to tweak some of the pseudo classes but it's still doable.
