### ISSUE TITLE
Truncation on flyout menu does not seem to work on Firefox

### ISSUE THREAD

**Issue by nhedger** [tailwindui/issues#192]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/elements/flyout-menus
- Component name: Full-width two-columns

**Describe the bug**
On Firefox, the blog article title does not get truncated. Instead it overflows from its container.

**To Reproduce**
1. Go to https://tailwindui.com/components/marketing/elements/flyout-menus
2. Scroll to "Full-width two-columns" component
3. Click on the "Solutions" menu item
2. See error

**Expected behavior**
The title should be truncated as it is truncated on Chrome.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/649677/81256807-de900880-9031-11ea-9f26-c8728ec991ad.png)

**Browser/Device (if applicable)**
 - OS: N/A
 - Browser: Mozilla Firefox
 - Version: 75

**Additional context**
This issue was reproduced by other community members on the following OS:
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0

**Comment by emarthinsen** [comment]
Was there a resolution to this issue? I'm still getting the same issue. I'm using Firefox 81.0 on Ubuntu 18.04. Here's a screenshot of what I'm seeing:

![tailwind](https://user-images.githubusercontent.com/135033/95263155-5d64b980-07fb-11eb-9573-ecd200752916.png)

This screenshot was taken from the https://tailwindui.com/components/marketing/elements/headers page.
