### ISSUE TITLE
Selected Radio Buttons are Oval / Oddly shaped

### ISSUE THREAD

**Issue by mab5vot9us9a** [tailwindui/issues#197]
**What component (if applicable)**
- https://tailwindui.com/components/application-ui/forms/form-layouts

**Describe the bug**
In Chrome on macOS, selected radio buttons are oddly shaped. (See Screenshot).
This does not happen in Chrome on Windows or any other Browser for that matter.

**To Reproduce**
1. use any of the provided [form layouts](https://tailwindui.com/components/application-ui/forms/form-layouts).
2. View the html in Chrome under macOS

**Expected behavior**
Have selected radio buttons be round.

**Screenshots**
<img width="1033" alt="Screenshot 2020-05-14 at 15 08 20" src="https://user-images.githubusercontent.com/8020703/81938727-9b1b3880-95f5-11ea-956d-81c9e02c6274.png">

**Browser/Device (if applicable)**
 - **OS:** macOS (10.15.4 (19E287))
 - **Browser:** Chrome (Version 81.0.4044.138 (Official Build) (64-bit))
- **yarn.lock:**
   - "@tailwindcss/custom-forms@^0.2.1"
   - "@tailwindcss/ui@^0.3.0"
   - tailwindcss@^1.4.6:

**tailwind.config.js**
```
module.exports = {
  purge: ["./src/**/*.html", "./src/**/*.vue", "./src/**/*.ts"],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [require("@tailwindcss/ui")],
};
```

**Comment by jasonlbeggs** [comment]
I'm not able to reproduce this issue in Chrome 83. Can you try upgrading your version of Chrome and trying again? Maybe it's an issue in your specific version of Chrome.

**Comment by mab5vot9us9a** [comment]
Hi Jason,
with Chrome 83 I am also no longer able to reproduce it. Thanks for looking into it!
