### ISSUE TITLE
Avatar with Initials

### ISSUE THREAD

**Issue by jeffsawatzky** [tailwindui/issues#199]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/avatars
- Component name: Circular avatars with placeholder initials

**Describe the bug**
Uses text-md which is not a class from what I can tell

**Comment by pqt** [comment]
It should probably be `text-base`.

**Comment by jeffsawatzky** [comment]
Or rename text-base to be text-md as this seems to be a common mistake people are making
