### ISSUE TITLE
Why doesn't my font pop like the example?

### ISSUE THREAD

**Issue by nmandal** [tailwindui/issues#207]
What am I doing wrong here?
<img width="1659" alt="Screen Shot 2020-05-20 at 6 55 35 PM" src="https://user-images.githubusercontent.com/20245409/82714098-dac7cd00-9c52-11ea-9554-ec8a0f8d3572.png">

I am using Ruby on Rails

**Comment by adamwathan** [comment]
There’s an annoying Chrome bug that was just fixed like yesterday where system fonts didn’t respect font weight on sizes over 20px. Try updating Chrome 👍🏻

**Comment by nmandal** [comment]
Yes - worked great! Thank you.

**Comment by sw-yx** [comment]
> There’s an annoying Chrome bug that was just fixed like yesterday where system fonts didn’t respect font weight on sizes over 20px

TIL, i thought i was going crazy! thanks adam
