### ISSUE TITLE
Question: Should red-900 and orange-900 both be #771D1D

### ISSUE THREAD

**Issue by ericxjohnston** [tailwindui/issues#211]
**What component (if applicable)**
- URL for category: https://www.npmjs.com/package/@tailwindcss/ui/v/0.3.0
- Component name: @tailwindcss/ui plugin 

**Describe the bug**
The hex value for red-900 and orange-900 are both #771D1D in the Tailwind UI plugin colors.js configuration. Is this correct?

**To Reproduce**
1. npm install @tailwindcss/ui
2. Open node_modules/@tailwindcss/ui/colors.js
3. View hex color values
```
red: {
    '900': '#771d1d',
  },
orange: {
    '900': '#771d1d',
  },
```
**Expected behavior**
Expected different values for each color.

**Comment by Apostolique** [comment]
What was the resolution to this? Were the colors changed behind the scene, or it's working as intended?

**Comment by adamwathan** [comment]
Sorry, the fixes are happening in a private repo which auto-closes issues here so it's easy to forget to comment here. We've fixed this internally but haven't published a new release yet, going to publish one now.

`red-900` is `#771d1d` and `orange-900` is `#73230d`.

**Comment by Apostolique** [comment]
Nice! You're awesome!

**Comment by ericxjohnston** [comment]
Thanks Adam! That's great. And thanks @Apostolique for following-up! I was wondering what the resolution was too. 😛
