### ISSUE TITLE
"form-select" rendering both the included svg and default drop-down icon

### ISSUE THREAD

**Issue by jacobpake** [tailwindui/issues#213]
When I use the `form-select` class I am seeing two drop down icons:

![form-select](https://i.imgur.com/zDbq7l3.png)

I expect to see:

![form-select](https://i.imgur.com/tqPZgwG.png)

Using TailwindCSS with the TailwindUI plugin on Firefox 76 on Ubuntu 20.04

The CSS class being produced is:

```
.form-select {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20' fill='none'%3e%3cpath d='M7 7l3-3 3 3m0 6l-3 3-3-3' stroke='%239fa6b2' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3e%3c/svg%3e");
  appearance: none;
  color-adjust: exact;
  background-repeat: no-repeat;
  background-color: #ffffff;
  border-color: #d2d6dc;
  border-width: 1px;
  border-radius: 0.375rem;
  padding-top: 0.5rem;
  padding-right: 2.5rem;
  padding-bottom: 0.5rem;
  padding-left: 0.75rem;
  font-size: 1rem;
  line-height: 1.5;
  background-position: right 0.5rem center;
  background-size: 1.5em 1.5em;
}
```

`appearance` is being considered an 'invalid property name' by the browser. 

On [the component page](https://tailwindui.com/components/application-ui/forms/input-groups) this is resolved by using `-moz-appearance: none;` however this does not seem to being included with the npm package

**Comment by rgdelato** [comment]
For adding browser-specific prefixes, you’ll probably want to also include a PostCSS plugin like “autoprefixer” or “postcss-preset-env” in addition to Tailwind.

**Comment by jacobpake** [comment]
Thank you, I'm now using autoprefixer which works as expected. This makes a lot of sense and is actually mentioned in the TailwindCSS docs.

I think this might be less obvious to some (at least me) than others but I'll close this as not a bug with TailwindUI.
