### ISSUE TITLE
"group" class used in Dropdown with Icons

### ISSUE THREAD

**Issue by jeffsawatzky** [tailwindui/issues#214]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/dropdowns#component-e4319217bff2762964fc89eb3382f911
- Component name: Dropdown with Icons

**Describe the bug**
Specifies a "group" class that doesn't exist. Maybe it's supposed to be "block"?

**Comment by Apostolique** [comment]
`group` is used with the `group-hover` and `group-focus` utilities. You can get more info from the docs: https://tailwindcss.com/docs/pseudo-class-variants/#group-hover

**Comment by jeffsawatzky** [comment]
Then why am I not able to do ‘@apply group;’ when trying to make a css component?

**Comment by Apostolique** [comment]
You'd need to create a css selector that targets the parent like:

```css
.group:hover child {
   @apply classes that you want to group with the parent.
}
```

Replace `.group` with your actual parent class and `child` with your child class.

Hopefully I didn't make a mistake, I wrote this on a phone.
