### ISSUE TITLE
Improper use of <dd>, <dt>, <dl> on Contact Sections - Side by Side Grid

### ISSUE THREAD

**Issue by kendalled** [tailwindui/issues#221]
**What component (if applicable)**
- URL for category: Contact Sections
- Component name: Side by Side Grid

**Describe the bug**
The phone numbers inside the larger `<dl>` elements are wrapped in a `<dl>` themselves. This caused a validation error. This was because of the nesting of `<dl>` elements and a lack of `<dt>` and `<dd>` pairs. Those elements simply needed to be changed to `<dd>` (creating that `<dt>` and `<dd>` pair)

**To Reproduce**
1. View source code
2. Validate
3. Scroll down to `<dl class="mt-2 text-base leading-6 text-gray-500">
              <div>
                <dt class="sr-only">
                  Email`

**Expected behavior**
Proper markup (not trying to be harsh, but I have to answer all the questions!)

**Browser/Device (if applicable)**
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
I will try to find if there are any more!

**Comment by adamwathan** [comment]
Oh wow good catch, will get this fixed. Thanks!
