### ISSUE TITLE
Modal leave transition not working if not wrapped with transition component

### ISSUE THREAD

**Issue by ifaniqbal** [tailwindui/issues#223]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/modals
- Component name: any modal

**Describe the bug**
I'm implementing with Vue. When the modal not wrapped with another transition component, leave transition won't work. This is because I need to wrap the root tag with state of the modal, like this:
```
<div
  v-show="modalOpen"
  class="fixed bottom-0 inset-x-0 px-4 pb-6 sm:inset-0 sm:p-0 sm:flex sm:items-center sm:justify-center">
  {{ snipped }}
</div>
```
And when I do that, the modal will just dissapear when the modalOpen is false.

That state (modalOpen) on modal root div tag is needed because only by doing that the other elements can be clicked.

**Comment by jasonlbeggs** [comment]
JS integrations are currently left up to users, but official Vue/Alpine/React components are in the plans, so I'm going to close this for now. Thanks!
