### ISSUE TITLE
Issue in documentation of  Card Heading With Action component

### ISSUE THREAD

**Issue by priyaprem** [tailwindui/issues#229]
component url: https://tailwindui.com/components/application-ui/headings/card-headings#component-9a0cf79b18a892dfed706f00447128e3
component name; card with action

**Describe the bug**
the card with action should have rounded component as given in the preview but the code doesnt involve any rounded

**To Reproduce**
1. Go to card with action component from card headings 
2. copy paste code to the tailwind playground 
3. we can see the card doesnt appear with rounded corners as given in the preview

**Expected behavior**
we require rounded corners in the code to make it as a complete component to serve purpose

**Screenshots**
![image](https://user-images.githubusercontent.com/37586565/85101430-04f3b700-b220-11ea-873a-e05bb0dd2cd5.png)

**Browser/Device (if applicable)**
 - OS: [e.g. iOS]windows 10
 - Browser chrome
 - Version Version 83.0.4103.106 

**Additional context**

**Comment by jasonlbeggs** [comment]
Hey @priyaprem! These components are meant to be inserted into existing cards. They're not really meant to be used on their own. They're sort of an add-on to an existing card. If you'd like to use the card heading as a standalone component in your project, add the following classes to the outermost div `bg-white overflow-hidden sm:rounded-lg sm:shadow`. Thanks!
