### ISSUE TITLE
Css clamp()

### ISSUE THREAD

**Issue by tanthammar** [tailwindui/issues#231]
I would be very interested in adding clamp() to the Tailwind library.
My thought was to keep the current naming but add -clamp-.

Some examples

dynamic font-sizing
text-clamp-2xl = font-size: clamp(1.25rem, (1rem + 5vw), 1.875rem); //with different values

dynamic margins
m-clamp-10 = margin: min(7vh, 2.75rem) 0 1.05rem;

dynamic widths
max-w-clamp-md = max-width: min(80%, 768px);

dynamic grid gaps
gap-clamp-4 : clamp(1rem, 2vw, 24px);

flex col width
flex-w-clamp-1/3 = flex-basis: max(30vw, 150px);

Inspiration:
https://ishadeed.com/article/css-min-max-clamp/

**Comment by jasonlbeggs** [comment]
Hey @tanthammar! That'd be a great idea for a plugin. It'd be more suited to be posted at https://github.com/tailwindcss/tailwindcss/discussions so the community can discuss it. I'm going to close this for now, but feel free to repost it over there. Thanks!
