### ISSUE TITLE
Contact Cards not looking good in safari

### ISSUE THREAD

**Issue by praveenperera** [tailwindui/issues#239]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/grid-lists#component-5d72b187beb968e12db89fe49f272b18
- Component name: Contact Cards

**Describe the bug**
Does not look good on Safari

Safari: 13.1.1
MacOS: 10.15.5 (19F101)

**To Reproduce**
1. Go to component in Safari

**Expected behavior**
Look like the preview

**Screenshots**
<img width="1477" alt="Screen Shot 2020-07-03 at 11 16 40 AM" src="https://user-images.githubusercontent.com/1775346/86482122-4eafc780-bd1f-11ea-97e3-e1ffae0b5663.png">

**Browser/Device (if applicable)**
 - OS: MacOS 10.15.5
 - Browser: Safari
 - Version: 13.1.1

**Comment by adamwathan** [comment]
Fixed thanks!
