### ISSUE TITLE
Contact card profile pictures broken on Mac Safari

### ISSUE THREAD

**Issue by bratsche** [tailwindui/issues#240]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/lists/grid-lists
- Component name: Contact cards

**Describe the bug**
The profile picture looks wrong on Safari (Mac). See screenshot attached below.

**Screenshots**
![Screen Shot 2020-07-03 at 10 19 15 AM](https://user-images.githubusercontent.com/2041/86482084-d8a76280-bd16-11ea-80e2-bef13a32f6c9.png)

**Browser/Device (if applicable)**
 - OS: MacOS Catalina
 - Browser: Safari
 - Version: 13.1.1 (15609.2.9.1.2

**Additional context**

**Comment by mstnorris** [comment]
They appear to be OK for me when using Safari 13.1.2

#### Screenshots
![Screenshot 2020-07-03 at 16 28 47](https://user-images.githubusercontent.com/1919816/86482872-b7f90000-bd4a-11ea-920d-bb844081c514.png)

#### Browser/Device
- OS: macOS Catalina 10.15.6 Beta (19G46c)
- Browser: Safari
- Version: 13.1.2 (15609.3.2)

**Comment by adamwathan** [comment]
Just fixed :) Thanks!

**Comment by bratsche** [comment]
Wow that was a quick fix! Thanks @adamwathan :)

**Comment by mstnorris** [comment]
@adamwathan curious as to what the issue was? What did you change?

**Comment by adamwathan** [comment]
There was an `h-0` on the wrapper element that held the photo/name/title, which was unnecessary. Habit from doing `w-0 flex-1` on horizontal elements.
