### ISSUE TITLE
Missing closing tag for img on heroes code for split with navbar

### ISSUE THREAD

**Issue by hoektoe** [tailwindui/issues#243]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes#component-e5c15b9d1a503738005e35302043c802
- Component name: heroes - split with navbar

**Describe the bug**
The <img> tag is missing closing slash. I believe this is why the indentation in code preview is incorrect.

**To Reproduce**
1. Go to https://tailwindui.com/components/marketing/sections/heroes#component-e5c15b9d1a503738005e35302043c802
2. Click on view code
3. Scroll down to last image with alt "Woman on her phone"
4. See no /> for image tag

**Expected behavior**
Indentation on document should be correct for code and image tag should end in slash />

**Additional context**
Excellent framework and great work with tailwindui

**Comment by mikebronner** [comment]
@hoektoe in HTML5 the closing slash on self-closing tags is optional. See http://xahlee.info/js/html5_non-closing_tag.html
