### ISSUE TITLE
Light sidebar with light header place holder div is missing height class

### ISSUE THREAD

**Issue by jasonbarrows** [tailwindui/issues#245]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/application-shells/sidebar#component-ba754bf465a594eb075045eb9e940b60
- Component name: Light sidebar with light header

**Describe the bug**
The content place holder has no height like the other layouts do.

**Screenshots**
<img width="1234" alt="Screenshot 2020-07-07 at 14 50 27" src="https://user-images.githubusercontent.com/440671/86791660-acb31680-c061-11ea-8217-ce30c323478f.png">

**Browser/Device (if applicable)**
 - OS: MacOS Ma
 - Browser: Chrome
 - Version: 83

**Additional context**
The div is missing a 

> h-96

 class

**Comment by bradlc** [comment]
Thanks!
