### ISSUE TITLE
Dropdown z index 

### ISSUE THREAD

**Issue by dillingham** [tailwindui/issues#25]
**What component (if applicable)**

- https://tailwindui.com/components/application-ui/elements/dropdowns
- https://tailwindui.com/components/application-ui/navigation/navbars

**Describe the bug**
When you copy a component with a dropdown..
The menu needs a `z-10` in order to not appear behind other elements.

**Comment by epixian** [comment]
In addition to putting `z-10` on the dropdown menu element, I also had to move the `z-0` from the parent `<span>` and put it on each of the `<button>`s.  Seems to fix the issue.

**Comment by thomasweitzel** [comment]
I stumbled across the same problem with the application shell (stacked layout) where I put a banner beneath the nav-bar: the menu with the transition from the nav-bar was behind the banner until I put a `z-10` on it (`<div x-show="open" x-transition:enter= ... class="... z-10"`). This problem seems to exist in various locations.

**Comment by dakira** [comment]
Also related #130.

**Comment by jasonlbeggs** [comment]
z-indexes are pretty context specific, so we try to not use them much more than necessary in Tailwind UI. It's probably best to just add them where necessary inside your own sites/apps unless it's an issue that will definitely be present in all cases. Thanks for submitting!

**Comment by shanerobinson** [comment]
While I agree z-index can be context specific, the **Profile dropdown** in the *Application > Navbars* will **ALWAYS** need a z-index: https://tailwindui.com/components/application-ui/navigation/navbars

I've added them for our use case but would be nice if the UI templates were updated for use in quick demos and boilerplates going forward.

**Comment by yogurtsyum** [comment]
Hey, sorry for responding to an issue so late but I'd like to share my solution for anyone else who finds this in the future. Assuming you're using the dropdown components TailwindUI provides, you can simply change `absolute` to `fixed` on the `<Menu.Items>` tag, and remove the `right-0` class. It's not ideal, but it seems to work for me.
