### ISSUE TITLE
Is it necessary to wrap buttons in spans

### ISSUE THREAD

**Issue by brucepom** [tailwindui/issues#252]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/elements/buttons
- Component name: Button

**Describe the bug**
Not really a bug. I'm just curious about the rationale for wrapping a `span` around every `button` bin the TailwindUI button examples. Since buttons are such a common element it would be nice to simplify the markup by skipping the span fi possible. If there's a reason for the span it's not a big deal to keep it, I just hadn't seen that before.

Thanks for the great work!

**Comment by Apostolique** [comment]
The reason is to allow the buttons to have a shadow while they are focused.

**Comment by brucepom** [comment]
Thanks for the explanation @Apostolique , good to know.
