### ISSUE TITLE
Missing Sidebar Navigation Mobile Menu

### ISSUE THREAD

**Issue by rushilsrivastava** [tailwindui/issues#254]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/sidebar-navigation
- Component name: Sidebar Navigation

**Describe the bug**
The previous Sidebar Navigations used to have a mobile menu it looks like that they have been removed on the new version.

**To Reproduce**
n/a

**Expected behavior**
Unclear if it was intentional since it was there before, was hoping there would be a mobile friendly responsive view.

**Screenshots**
n/a

**Browser/Device (if applicable)**
n/a

**Additional context**
n/a

**Comment by adamwathan** [comment]
Hey! The sidebar _layouts_ do have collapsable mobile menus, they are still there and were not removed:

https://tailwindui.com/components/application-ui/application-shells/sidebar

The new sidebar _navigation_ category are just sidebar examples that are meant to be dropped in to replace those existing layouts. We'll also be creating alternate mobile menus soon that will also go in their own category 👍
