### ISSUE TITLE
Headers & drop downs separated

### ISSUE THREAD

**Issue by dillingham** [tailwindui/issues#255]
Currently when I go to snag a header.. it comes with a huge amount of markup and is kinda confusing

Can the current layouts be added to "Navbars" without the dropdowns?

**Comment by adamwathan** [comment]
Just to be totally clear, do you mean the marketing headers/navbars here?

https://tailwindui.com/components/marketing/elements/headers

**Comment by dillingham** [comment]
@adamwathan yeah, I always think "header" when I really should be going to "navbars"

https://tailwindui.com/components/application-ui/navigation/navbars

But I like the centered links & link / button combo on the right

Was just wondering if they could be included in the navbar section minus the extras.

**Comment by dillingham** [comment]
Whoops, nevermind just realized its apart of the other pack.
