### ISSUE TITLE
Thin white border-top on Table Row evident when changing background color

### ISSUE THREAD

**Issue by bgold0** [tailwindui/issues#27]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/tables/wide
- Component name: Table

**Describe the bug**
I'm trying to make a dark theme for your Table component but I'm getting stuck with a White border at the top of my rows.

**To Reproduce**
Add a background to body, copy the table component, and change the backgrounds of the rows to a darker shade.

**Expected behavior**
No white border

**Video**
https://streamable.com/3f9l6

**Browser/Device (if applicable)**
 - OS: Mac OS
 - Browser Chrome

**Comment by bgold0** [comment]
Was able to solve this by doing:

```
tr { border-style: hidden }
```

**Comment by mikebronner** [comment]
You might also try instead:
```css
tr {
@apply border-t-0;
}
```

I've found that using border-style hidden can. Abuse unexpected complications if you to want a border in other areas later.

**Comment by bgold0** [comment]
@mikebronner That was the first thing that came to mind but unfortunately doesn't remove the white space.

**Comment by mikebronner** [comment]
@bgold0 Gotcha ...

**Comment by jasonlbeggs** [comment]
@bgold0 can you confirm this is still an issue? I'm having trouble reproducing it. If I use dark backgrounds and remove the `border-b` class on each `th` element it appears fine for me.

**Comment by jasonlbeggs** [comment]
I'm going to close this issue for now. If you find the time to provide a code snippet that reproduces the issue, feel free to re-open it. Thanks!
