### ISSUE TITLE
Background square patterns not always showing

### ISSUE THREAD

**Issue by imacrayon** [tailwindui/issues#36]
**What component (if applicable)**
- URL for category:
    - https://tailwindui.com/components/marketing/sections/heroes
    - https://tailwindui.com/components/marketing/sections/testimonials
- Component name: 
    - Simple centered
    - With large avatar

**Describe the bug**
There are conflicting `id`s for the SVGs that produce the background pattern of gray squares. When the `id` for two pattern SVGs are the same the second SVG won't show on the page.

**To Reproduce**
1. Place a "Simple centered" hero and "With large avatar" testimonial on the same page.
2. The squares pattern only appears for the first component on the page.

**Expected behavior**
The squares pattern should appear in both components.

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser: Firefox
 - Version 74.0b3

**Comment by adamwathan** [comment]
Good catch, this is a super annoying problem with inline SVGs 

Just pushed a change that uses a unique UUID for every pattern ID to solve this 👍
