### ISSUE TITLE
Pagination suggestion: disabled/active

### ISSUE THREAD

**Issue by lol768** [tailwindui/issues#4]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/pagination
- Component name: Pagination

**Describe the bug**

Can you add examples of disabled (e.g. prev/next when on first/last page) and currently active page, please?

**Comment by jasonlbeggs** [comment]
I'm going to close this issue for now since it's not really a bug, but I'll leave #171 open as a reminder to revisit this improvement in the future. Thanks!
