### ISSUE TITLE
Marketing: Angled image on right navigation partially blocked by angled image SVG

### ISSUE THREAD

**Issue by mike1o1** [tailwindui/issues#43]
**Marketing - Page Sections - Hero Sections**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes
- Component name: With angled image on right

**Describe the bug**
The white SVG element for the angled image is partially blocking the "log in" link making it impossible to click on the right half of it as it's layered on top if the navigation section.

**To Reproduce**
1. Go to marketing heroes section
2. View the angled image on right sample
3. Try and click or hover on the right half of "Log in" link

**Expected behavior**
User should be able to click or hover over the entire "Log in" link.

**Screenshots**
![image](https://user-images.githubusercontent.com/837213/76046958-2c936d80-5f16-11ea-9704-964aab9940ce.png)

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser Chrome, Safari, etc.
 - Version 80

**Additional context**
Giving the svg element a z-index of -1 seems to fix the issue.

**Comment by jasonlbeggs** [comment]
This bug was recently fixed. Thanks!
