### ISSUE TITLE
Applications | Form | Labels on left input width inconsistent on mobile

### ISSUE THREAD

**Issue by jfreeze** [tailwindui/issues#51]
**What component (if applicable)**
- URL for category: Applications | Form
- Component name: Labels on left Preview

**Describe the bug**

It may be intentional, but the email address and the street address input sections are longer than the surrounding input sections. On mobile, they are slightly larger and appear as a mistake.

**Comment by jasonlbeggs** [comment]
This has been fixed now! Thanks for the suggestion.
