### ISSUE TITLE
Description List tags are semanticly reversed

### ISSUE THREAD

**Issue by jroski** [tailwindui/issues#52]
**What component (if applicable)**
https://tailwindui.com/components/application-ui/data-display/description-lists

**Describe the bug**
`<dd>` and `<dt>` tags are semanticly reversed. 

**To Reproduce**
1. View code for any of the description list components.

**Expected behavior**
`<dt>` Should define a term/name, `<dd>` should be the definition.

**Comment by adamwathan** [comment]
Well that's embarrassing, thank you, deploying a fix now!
