### ISSUE TITLE
Copy to clipboard output can be changed by typing

### ISSUE THREAD

**Issue by Welfordian** [tailwindui/issues#58]
**What component (if applicable)**
- URL for category: Any component

**Describe the bug**
When clicking the copy icon on any component page, if you start typing and click the copy button again, the copied result is whatever was typed.

This can also be achieved by just focusing on a copy button... typing and then clicking the copy button.

**To Reproduce**
1. Go to any component page
2. Click the copy icon
3. Begin typing
4. Click the copy icon again

**Screenshots**
https://youtu.be/BKDMUcai9x0

**Browser/Device (if applicable)**
 - OS: MacOS 10.15.3
 - Browser Chrome
 - Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by adamwathan** [comment]
Hah nice find! Made the hidden textareas `readonly` which seems to fix this 👍 Thanks!
