### ISSUE TITLE
Empty placeholder in the first_name input field

### ISSUE THREAD

**Issue by PhiloNL** [tailwindui/issues#6]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Labels on left

**Describe the bug**
Just a small thing, there is an empty placeholder for the `first_name` input field.

**To Reproduce**
Check the code for the Labels on left component:
 
```html
<input id="first_name" placeholder=" " class="form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" />
```

**Expected behavior**
`placeholder=" "` should be removed from the component.

**Comment by adamwathan** [comment]
Thanks, removed it and pushed it out 👍🏻 

For anyone curious this is an artifact from me trying to troubleshoot this weird Safari flexbox bug where `items-baseline` doesn't work when you are trying to align an input and a piece of text:

https://bugs.webkit.org/show_bug.cgi?id=142968

Adding an empty placeholder "fixes" the bug but that seemed like a bad fix, so instead did the alignment manually and got rid of `items-baseline` 🙃
