### ISSUE TITLE
bg-gray-50 isn't working for me

### ISSUE THREAD

**Issue by bgold0** [tailwindui/issues#60]
**What component (if applicable)**
- URL for category:   https://tailwindui.com/components/application-ui/overlays/modals
- Component name:  Simple with gray footer Modal

**Describe the bug**
When trying `bg-gray-50` in the last part of this modal, the background doesn't change. Also not quite sure why the text color looks a bit different (I'm using Inter.css)

**To Reproduce**
1. Simple copy and paste of the code in the above link
2. No background change

**Screenshots**
![image](https://user-images.githubusercontent.com/4645400/76152101-a8fa8d80-6089-11ea-9817-37d7f8c9bc3c.png)

**Expected**
![image](https://user-images.githubusercontent.com/4645400/76152109-c3cd0200-6089-11ea-961a-40f0fc842087.png)

**Browser/Device (if applicable)**
 - OS: OSX
 - Browser Chrome

**Comment by merelinguist** [comment]
Have you added the `@tailwindcss/ui` plugin, as [dictated by the docs](https://www.notion.so/Tailwind-UI-Documentation-f9083ed0e2694690ac89253e88afb2b6#c9efa316d69a444fa0bafc69ca4d0966)?

**Comment by bgold0** [comment]
Yup, my `tailwind.config.js` is:

```
let defaultTheme = require('tailwindcss/defaultTheme');
module.exports = {
	theme: {
		extend: {
			fontFamily: {
				sans: ['Inter var', ...defaultTheme.fontFamily.sans]
			}
		},
		colors: {
			primary: {
				900: 'var(--color-primary-900)',
				800: 'var(--color-primary-800)',
				700: 'var(--color-primary-700)',
				600: 'var(--color-primary-600)',
				500: 'var(--color-primary-500)',
				400: 'var(--color-primary-400)',
				300: 'var(--color-primary-300)',
				200: 'var(--color-primary-200)',
				100: 'var(--color-primary-100)'
			},
			...defaultTheme.colors
		}
	},
	variants: {
		// Some useful comment
	},
	plugins: [require('@tailwindcss/ui')]
};
```

And I have it installed in my package.json. Is there something specific I can search for in my rendered styles to make sure it's there?

**Comment by bgold0** [comment]
It was the `...defaultTheme.colors` that was causing issues. When I removed it it ended up working.
