### ISSUE TITLE
Mix fixed with auto width in Tables

### ISSUE THREAD

**Issue by ivosabev** [tailwindui/issues#66]
I've experimented with different options, but could not find a way to solve this properly using TailwindUI and TailwindCSS , any ideas? Is the component and framework lacking something or is it me?

**Comment by adamwathan** [comment]
Hey @ivosabev! Can you give an example of what you mean? Are you talking about column sizes, like having one column be explicitly 50% but the rest be automatically sized based on content? If so I think this is currently impossible with CSS unfortunately.

**Comment by ivosabev** [comment]
Here is an working example of mixing PX, % and auto widths.

https://jsbin.com/revipivoke/edit?html,output

**Comment by jasonlbeggs** [comment]
I'm closing this issue now as it doesn't really pertain to Tailwind UI. If you can provide a more concrete example based on a Tailwind UI component, please re-open. Thanks!
