### ISSUE TITLE
Old flex-no-shrink on Toggle elements

### ISSUE THREAD

**Issue by joaokamun** [tailwindui/issues#67]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/toggles
- Component name: Toggles

**Describe the bug**
All toggle elements has the old `flex-no-shrink` instead of `flex-shrink-0`

**Comment by adamwathan** [comment]
Wow that's a dumb mistake, thanks 😅 Never make breaking changes to your open source libraries folks.

Pushing the change now!
