### ISSUE TITLE
Inconsistencies across classes/markup for the various Sidebar layouts

### ISSUE THREAD

**Issue by moollaza** [tailwindui/issues#70]
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/application-shells/sidebar
- Component name: Sidebar layout

**Describe the bug**
Inconsistencies across the code in the various examples. I think the first example's code is correct, but I started with the dark sidebar and noticed some differences between that and the branded sidebar.

For example, in the Branded Sidebar, when the sidebar is open on a mobile sized screen, clicking the gray overlay to the side doesn't hide the menu. For the "Dark Sidebar" (and others), it hides the sidebar.

In the markup below the mobile sidebar in the "Branded Sidebar" there is an extra div/comment as well:
```html
<div class="flex-shrink-0 w-14">
<!-- Force sidebar to shrink to fit close icon -->
</div>
```

**To Reproduce**
1. https://tailwindui.com/components/application-ui/application-shells/sidebar
2. Get the code for the "Dark Sidebar" and compare it to "Light Sidebar" and "Brand sidebar with light header" -- there are subtle differences in the classes and appears to be a few duplicated/missing classes.

**Expected behavior**
All code should be the same, aside from the different elements in the design

**Screenshots**
n/a

**Browser/Device (if applicable)**
 - OS: Mac
 - Browser Firefox

**Additional context**
Happy to provide further examples. I think just rendering each of these will make it clear whats broken/missing in some examples

**Comment by moollaza** [comment]
Just took another look at the markup and it seems like things are correct. Perhaps it's been fixed, or somehow I copied it wrong a few days ago :+1:

**Comment by moollaza** [comment]
Reopening as I've noticed another bug. Description is updated.

**Comment by adamwathan** [comment]
Hey! Yep this is all related to this issue: https://github.com/tailwindui/issues/issues/2

Making those fixes will fix what you've pointed out here so I'm going to close this as essentially a duplicate. Planning to get those fixes out today 👍🏻
