### ISSUE TITLE
Ellipsis truncation not working on some Description Lists on Firefox

### ISSUE THREAD

**Issue by inopinatus** [tailwindui/issues#71]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/data-display/description-lists
- Component name: _Left-aligned in card_, _left-aligned_, and _two-column in card_

Not affected: _Left-aligned striped in card_

**Describe the bug**

In very narrow viewports, the filenames in the attachment lists are not truncated with ellipsis on Firefox. 

**To Reproduce**
1. Go to Description Lists
2. Drag each width slider to be very narrow
3. See error

**Expected behavior**

truncation with ellipsis in all attachment lists

**Screenshots**

Side-by-side between bad and good:

<img width="1079" alt="Screen Shot 2020-03-09 at 18 59 28" src="https://user-images.githubusercontent.com/938619/76186927-c457cb00-6238-11ea-87e2-65d106409b78.png">

**Browser/Device (if applicable)**
 - macOS Catalina 10.15.3
 - Firefox 73.0.1 and Firefox Dev Edition 74.0b9

**Additional context**

Looks like dissimilar classes on the span.

**Comment by adamwathan** [comment]
Just pushed a fix, thanks for catching! The trick is to add `flex-1 w-0` to the span elements that have the file names in them 👍
