### ISSUE TITLE
Three-tier pricing component has height issues for left/right tiers

### ISSUE THREAD

**Issue by kahkeng** [tailwindui/issues#77]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/pricing
- Component name: Three tiers with emphasized tier

**Describe the bug**
The left and right tiers seem to have incorrect heights in various browsers.

**To Reproduce**
1. Start with empty page:
```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link rel="stylesheet" href="/build/tailwind.css">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.0.1/dist/alpine.js" defer></script>
</head>
<body>
</body>
</html>
```
2. Copy component code into the body.
3. Visit resulting page in various browsers.
4. See incorrect heights in components (see screenshots). This doesn't happen when viewing the component in the gallery iframe.

**Expected behavior**
Component should not have a lot of whitespace nor extend to the full height of the window.

**Screenshots**
On FireFox v73.0.1 (same issue on Chrome v80):
Above test page (this looks too tall):
<img width="472" alt="Screen Shot 2020-03-12 at 12 27 37 AM" src="https://user-images.githubusercontent.com/141746/76497560-78538480-63f8-11ea-830d-c3c8a037371f.png">
Inside gallery (this looks right): 
<img width="455" alt="Screen Shot 2020-03-12 at 12 40 08 AM" src="https://user-images.githubusercontent.com/141746/76498456-23b10900-63fa-11ea-838a-26ba3d31ff12.png">

On Safari v10.1.2:
Above test page (side tiers are very tall): 
<img width="1226" alt="Screen Shot 2020-03-12 at 12 30 17 AM" src="https://user-images.githubusercontent.com/141746/76497663-ae910400-63f8-11ea-9d6c-8b8665c4cdf1.png">

Inside gallery (side tiers are missing): 
<img width="1204" alt="Screen Shot 2020-03-12 at 12 41 51 AM" src="https://user-images.githubusercontent.com/141746/76498522-4a6f3f80-63fa-11ea-89fe-79c3af158af3.png">

**Browser/Device (if applicable)**
 - OS: MacOS, also iOS
 - Browser/Version: see above

**Additional context**
I believe this is caused by the `h-full` class. But omitting it or using `lg:h-full` doesn't seem to help, but instead causes different set of issues.

**Comment by adamwathan** [comment]
Hmm I can't seem to replicate this, any chance you can replicate it in a CodePen or JSFiddle or similar?

This is what I get in Safari for example:

![image](https://user-images.githubusercontent.com/4323180/76983082-343e1380-6913-11ea-9a73-0d098a8c5ce5.png)

**Comment by kahkeng** [comment]
Thanks for looking into it and suggesting debugging with CodePen. It also didn't reproduce there and after some digging, I found that:
- the Firefox issue with height is due to me missing `<!DOCTYPE html>` declaration in my file (oops).
- the IE issue is because my Safari browser is too old.

I'll close this now given this isn't a bug. Thanks!
