### ISSUE TITLE
Typo: Large avatar testimonials

### ISSUE THREAD

**Issue by Sjoerrdd** [tailwindui/issues#79]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/testimonials
- Component name: With large avatar

**Describe the bug**
The name div has a typo

**To Reproduce**
1. Go to 'https://tailwindui.com/components/marketing/sections/testimonials'
2. Scroll down to 'With large avatar'
3. Click on code
4. CMD + F for 'Judith Black'
4. See typo 'grya'

**Expected behavior**
n/a

**Screenshots**
<img width="329" alt="Schermafbeelding 2020-03-12 om 13 12 25" src="https://user-images.githubusercontent.com/19862992/76520849-f8fb9a80-6463-11ea-98a6-d2847473275e.png">

**Browser/Device (if applicable)**
 - OS: MacOS 10.15.3
 - Browser: Chrome
 - Version: 80

**Comment by adamwathan** [comment]
Fixed, thank you! ❤️
