### ISSUE TITLE
spacing with . like 'px-2.5' not working with @apply or theme()

### ISSUE THREAD

**Issue by julianstark999** [tailwindui/issues#83]
**What component (if applicable)**
- Component name: @tailwindcss/ui spacing

**Describe the bug**
I tried to `@apply` (`theme('')`) one of the new spacings to build a css component, but it doesn't work.
Multiple ways doesn't work:

- @apply px-2.5;
- @apply px-2\\.5;
- theme('spacing.2.5');
- theme('spacing.2\\.5');

**To Reproduce**
1. require `@tailwindcss/ui` in tailwind.config.js
2. `@apply px-2.5` inside .less file

**Screenshots**
`@apply px-2.5;` in less
![@apply px-2.5](https://user-images.githubusercontent.com/7670380/76643772-06914d00-6556-11ea-915d-a9ca8b21cfbd.png)
`@apply px-2\.5;` in less
![@apply px-2\.5](https://user-images.githubusercontent.com/7670380/76643981-6982e400-6556-11ea-9629-a9b231d4da37.png)

**Comment by adamwathan** [comment]
I just tested this and works the way I expect:

```css
.foo {
  @apply px-2.5;
}
```

Notice that I didn't escape the `.` at all, could be your issue?

To use `theme`, use array notation like this:

```css
.foo {
  padding: theme('spacing[2.5]');
}
```

**Comment by julianstark999** [comment]
Thanks. The array notation for `theme` works perfectly. 

With `@apply` it still doesn't work even though I tried it as used in your first example and my first screenshot

**Comment by adamwathan** [comment]
Testing it looks like this is because of how Less is trying to parse the CSS. You can get past it using [string escaping](http://lesscss.org/functions/#string-functions-e) in Less like this:

```less
.foo {
  @apply e("px-2.5");
}
```
