### ISSUE TITLE
Simple no labels: invalid classes

### ISSUE THREAD

**Issue by vesper8** [tailwindui/issues#85]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/sign-in-forms
- Component name: Simple no labels

**Describe the bug**
Found these invalid classes that are neither part of tailwindcss 1.2 or @tailwindcss/ui
`max-w`
`inset-y`

![Screen Shot 2020-03-14 at 8 02 11 PM](https://user-images.githubusercontent.com/816028/76687658-c6ea6400-662e-11ea-8d52-d26d09a48dcb.png)
![Screen Shot 2020-03-14 at 8 02 00 PM](https://user-images.githubusercontent.com/816028/76687659-c782fa80-662e-11ea-9830-a22816342e26.png)

**Comment by adamwathan** [comment]
Yikes not sure how this happened, thanks for catching, pushing a fix now.
