### ISSUE TITLE
Black Dot Background

### ISSUE THREAD

**Issue by Chazza** [tailwindui/issues#9]
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes
- Component name: With sign up and media content

**Describe the bug**
The right dots appear with a black background in the wrong place.

**To Reproduce**
1. Go to the template.
2. Copy into your file.
3. View in the browser.

**Expected behavior**
Dots appear on the right as shown in the preview.

**Screenshots**
https://i.imgur.com/CqxOtSx.png

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome (Brave)
 - Version [e.g. 22] 1.3.118

**Comment by dillingham** [comment]
I experienced that when I didn’t have the tailwindcss/ui npm package installed 

I’m sure a lot of people are bumping into this as I originally assumed 1.2 would cover it seamlessly. Not that it’s a problem, just an assumption others may be having.

**Comment by Chazza** [comment]
> I experienced that when I didn’t have the tailwindcss/ui npm package installed
> 
> I’m sure a lot of people are bumping into this as I originally assumed 1.2 would cover it seamlessly. Not that it’s a problem, just an assumption others may be having.

Mine turned out to be the default 1.2 config with the plugin added, when I used the empty config it worked fine.

Perhaps still flag this as a bug?

**Comment by adamwathan** [comment]
This sounds related to this probably:

https://github.com/tailwindui/issues/issues/12

If you use the complete (`--full` flag) default 1.2 config then you are preventing the plugin from adding its extensions. Use the empty config and you're good to go.

**Comment by adamwathan** [comment]
Closing as 99% sure it's the issue I mentioned, if it still persists though please let me know and I will help sort it out for you.
