### ISSUE TITLE
Colors do not match Tailwind CSS themes and Tailwind UI

### ISSUE THREAD

**Issue by bujordet** [tailwindui/issues#94]
[https://tailwindcss.com/docs/customizing-colors#default-color-palette](https://tailwindcss.com/docs/customizing-colors#default-color-palette)

The colors provided in the link over, and in many themes, are not the same as those used in tailwindUI components. Inspecting the components gives gray-900 is #161E2E on the site and  #1A202C in the Color palette.

Example with badge:
![image](https://user-images.githubusercontent.com/16757653/77157216-33d38300-6aa1-11ea-8318-1a8ed65ec0be.png)

![image](https://user-images.githubusercontent.com/16757653/77157324-68473f00-6aa1-11ea-988e-eab8509fa00e.png)

**Browser/Device (if applicable)**
 - OS: Mac OS Catalina 10.15.2
 - Browser chrome
 - Version 80.0.3987.132

**Comment by adamwathan** [comment]
Tailwind UI uses a new color palette which we will be adding to Tailwind core in a future version:

https://www.notion.so/How-Tailwind-UI-Extends-Tailwind-2f74104b886c47b3b7a24a65f1d24935

The new colors are better, we struggled to achieve the designs we wanted with the old color system 👍🏻

You get this new color palette when you install the Tailwind UI plugin:

https://www.notion.so/Tailwind-UI-Documentation-f9083ed0e2694690ac89253e88afb2b6#c9efa316d69a444fa0bafc69ca4d0966
